language: node_js
node_js: stable
cache:
  directories:
  - node_modules
before_install:
- echo "TZ='Asia/Shanghai'; export TZ" >> ~/.profile
- . ~/.profile
- openssl aes-256-cbc -K $encrypted_023c3608ff03_key -iv $encrypted_023c3608ff03_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git clone -b master "$REPO" .deploy_git
- git clone -b gitbook "$REPO_DOCS" source/_posts
- cd source/_posts
- rm -rf php
- git clone -b gitbook "$REPO_PHP_DOCS" php
- cd ../../
install:
- ls -la
#- npm install
script:
- ./node_modules/hexo/bin/hexo g
- ./node_modules/hexo/bin/hexo d
branches:
  only:
  - hexo
env:
  global:
  - REPO_DOCS: git@github.com:khs1994-website/docs.git
  - REPO_PHP_DOCS: git@github.com:khs1994-website/php-docs.git
  - REPO: git@github.com:khs1994/khs1994.github.io.git
addons:
  ssh_known_hosts:
  - code.aliyun.com
